/**
 * Seeded matrix cells — agent surfaces. Real content throughout: this
 * project's own registry, models, and run states a stranger can read.
 */
import * as React from 'react';
import { Text } from 'react-native';

import { Agent, AgentActions, AgentContent, AgentHeader } from '@/components/ai/agent';
import {
  Artifact,
  ArtifactAction,
  ArtifactActions,
  ArtifactClose,
  ArtifactContent,
  ArtifactDescription,
  ArtifactHeader,
  ArtifactTitle,
} from '@/components/ai/artifact';
import {
  Attachment,
  AttachmentEmpty,
  AttachmentInfo,
  Attachments,
} from '@/components/ai/attachments';
import {
  AudioPlayer,
  AudioPlayerControlBar,
  AudioPlayerDurationDisplay,
  AudioPlayerMuteButton,
  AudioPlayerPlayButton,
  AudioPlayerSeekBackwardButton,
  AudioPlayerSeekForwardButton,
  AudioPlayerTimeDisplay,
  AudioPlayerTimeRange,
  AudioPlayerVolumeRange,
} from '@/components/ai/audio-player';
import {
  ChainOfThought,
  ChainOfThoughtContent,
  ChainOfThoughtHeader,
  ChainOfThoughtStep,
} from '@/components/ai/chain-of-thought';
import {
  Confirmation,
  ConfirmationAction,
  ConfirmationActions,
  ConfirmationRequest,
  ConfirmationTitle,
} from '@/components/ai/confirmation';
import { Context, ContextTrigger } from '@/components/ai/context';
import { Image } from '@/components/ai/image';
import { MicSelector, MicSelectorTrigger, MicSelectorValue } from '@/components/ai/mic-selector';
import { ModelSelector, ModelSelectorTrigger } from '@/components/ai/model-selector';
import { OpenIn, OpenInTrigger } from '@/components/ai/open-in-chat';
import { Persona } from '@/components/ai/persona';
import {
  Plan,
  PlanContent,
  PlanDescription,
  PlanHeader,
  PlanProgressBadge,
  PlanTitle,
} from '@/components/ai/plan';
import {
  Queue,
  QueueItem,
  QueueItemContent,
  QueueItemDescription,
  QueueItemRemove,
  QueueList,
  QueueSection,
  QueueSectionTrigger,
} from '@/components/ai/queue';
import {
  Question,
  QuestionOption,
  QuestionOptions,
  QuestionPrompt,
} from '@/components/ai/question';
import { Shimmer } from '@/components/ai/shimmer';
import { SpeechInput } from '@/components/ai/speech-input';
import {
  VoiceSelector,
  VoiceSelectorTrigger,
} from '@/components/ai/voice-selector';
import { TaskItem } from '@/components/ai/task';
import type { ItemCells } from '../cells';

const MODEL_ID = 'claude-fable-5-1';
const AVATAR_URI =
  'https://raw.githubusercontent.com/hackerpug-ai/rnr-ai-elements/v0.2.0/assets/images/icon.png';

export const AI_AGENT_CELLS: Record<string, ItemCells> = {
  agent: {
    populated: (o) => (
      <Agent
        runStatus={(o.runStatus as 'idle' | 'running' | 'paused' | 'error' | 'done') ?? 'running'}
        onRunAction={() => {}}
      >
        <AgentHeader
          name="Registry Porter"
          description="Installs the 56-item set into consumer apps"
          avatarUri={AVATAR_URI}
        />
        <AgentContent>
          <Text className="text-sm text-muted-foreground">
            Run 12 · installing conversation.json through the RNR CLI
          </Text>
        </AgentContent>
        <AgentActions />
      </Agent>
    ),
    empty: () => (
      <Agent runStatus="idle">
        <AgentHeader name="Registry Porter" description="No run started" />
      </Agent>
    ),
    loading: () => (
      <Agent runStatus="running">
        <AgentHeader name="Registry Porter" description="Resolving item graph…" avatarUri={AVATAR_URI} />
        <AgentContent>
          <Shimmer active>
            <Text className="text-sm">Resolving registry dependencies…</Text>
          </Shimmer>
        </AgentContent>
      </Agent>
    ),
    error: () => (
      <Agent runStatus="error">
        <AgentHeader name="Registry Porter" description="Install failed at the pinned tag" avatarUri={AVATAR_URI} />
        <AgentContent>
          <Text className="text-sm text-destructive">404 — item not found at v0.2.0</Text>
        </AgentContent>
      </Agent>
    ),
  },
  artifact: {
    populated: () => (
      <Artifact>
        <ArtifactHeader>
          <ArtifactTitle>gallery-manifest.ts</ArtifactTitle>
          <ArtifactDescription>The derived gallery item list — 56 entries, never hand-edited</ArtifactDescription>
          <ArtifactActions>
            <ArtifactAction icon={undefined} label="Download" onPress={() => {}} />
            <ArtifactClose />
          </ArtifactActions>
        </ArtifactHeader>
        <ArtifactContent>
          <Text className="text-sm text-muted-foreground">Generated by scripts/build-gallery-manifest.ts</Text>
        </ArtifactContent>
      </Artifact>
    ),
    empty: () => (
      <Artifact>
        <ArtifactHeader>
          <ArtifactTitle>(no artifact yet)</ArtifactTitle>
        </ArtifactHeader>
        <ArtifactContent>
          <Text className="text-sm text-muted-foreground">The run has not produced a deliverable</Text>
        </ArtifactContent>
      </Artifact>
    ),
    loading: () => (
      <Artifact>
        <ArtifactHeader>
          <Shimmer active>
            <Text className="text-sm">Generating artifact…</Text>
          </Shimmer>
        </ArtifactHeader>
      </Artifact>
    ),
    error: () => (
      <Artifact>
        <ArtifactHeader>
          <ArtifactTitle>artifact.json</ArtifactTitle>
          <ArtifactDescription>Generation stopped mid-write</ArtifactDescription>
        </ArtifactHeader>
        <ArtifactContent>
          <Text className="text-sm text-destructive">Truncated at 4 KB — the stream dropped</Text>
        </ArtifactContent>
      </Artifact>
    ),
  },
  attachments: {
    populated: () => (
      <Attachments variant="list">
        <Attachment
          data={{
            id: 'att-1',
            name: 'registry-manifest.pdf',
            mimeType: 'application/pdf',
            sizeBytes: 48213,
          }}
          state="done"
          onRemove={() => {}}
        >
          <AttachmentInfo showMediaType />
          <AttachmentInfo />
        </Attachment>
        <Attachment
          data={{ id: 'att-2', name: 'cold-boot.png', mimeType: 'image/png', sizeBytes: 118_402 }}
          state="uploading"
        >
          <AttachmentInfo />
        </Attachment>
      </Attachments>
    ),
    empty: () => (
      <Attachments variant="list">
        <AttachmentEmpty />
      </Attachments>
    ),
    loading: () => (
      <Attachments variant="list">
        <Attachment
          data={{ id: 'att-3', name: 'engine-parity-proof.md', mimeType: 'text/markdown' }}
          state="uploading"
        >
          <AttachmentInfo />
        </Attachment>
      </Attachments>
    ),
    error: () => (
      <Attachments variant="list">
        <Attachment
          data={{ id: 'att-4', name: 'oversized-transcript.json', mimeType: 'application/json' }}
          state="error"
        >
          <AttachmentInfo />
        </Attachment>
      </Attachments>
    ),
  },
  'audio-player': {
    populated: () => (
      <AudioPlayer isPlaying={false} positionMs={41_200} durationMs={187_000} volume={0.8}>
        <AudioPlayerControlBar>
          <AudioPlayerSeekBackwardButton />
          <AudioPlayerPlayButton />
          <AudioPlayerSeekForwardButton />
          <AudioPlayerMuteButton />
          <AudioPlayerTimeDisplay />
          <AudioPlayerDurationDisplay />
        </AudioPlayerControlBar>
        <AudioPlayerTimeRange />
        <AudioPlayerVolumeRange />
      </AudioPlayer>
    ),
    empty: () => (
      <AudioPlayer positionMs={0} durationMs={0}>
        <AudioPlayerControlBar>
          <AudioPlayerPlayButton />
          <AudioPlayerTimeDisplay />
        </AudioPlayerControlBar>
      </AudioPlayer>
    ),
    loading: () => (
      <AudioPlayer isPlaying durationMs={0} positionMs={0}>
        <AudioPlayerControlBar>
          <AudioPlayerPlayButton />
          <Shimmer active>
            <Text className="text-sm">buffering generated audio…</Text>
          </Shimmer>
        </AudioPlayerControlBar>
      </AudioPlayer>
    ),
    error: () => (
      <AudioPlayer positionMs={0} durationMs={0}>
        <AudioPlayerControlBar>
          <AudioPlayerPlayButton />
          <Text className="text-sm text-destructive">Playback failed — the audio URI expired</Text>
        </AudioPlayerControlBar>
      </AudioPlayer>
    ),
  },
  'chain-of-thought': {
    populated: (o) => (
      <ChainOfThought defaultOpen={o.defaultOpen === true} isStreaming={o.isStreaming === true}>
        <ChainOfThoughtHeader
          label="Porting web-preview"
          steps={[{ status: 'completed' }, { status: 'running' }, { status: 'pending' }]}
        />
        <ChainOfThoughtContent>
          <ChainOfThoughtStep label="Read the web original" description="web-preview.tsx:1-260" status="completed" />
          <ChainOfThoughtStep label="Swap the iframe" description="react-native-webview with the scheme allowlist" status="running" />
          <ChainOfThoughtStep label="Declare the peer" description="react-native-webview in registry.json" status="pending" isLast />
        </ChainOfThoughtContent>
      </ChainOfThought>
    ),
    empty: () => (
      <ChainOfThought>
        <ChainOfThoughtHeader label="Chain of thought" />
        <ChainOfThoughtContent>
          <ChainOfThoughtStep label="(no steps yet)" isLast />
        </ChainOfThoughtContent>
      </ChainOfThought>
    ),
    loading: () => (
      <ChainOfThought isStreaming defaultOpen>
        <ChainOfThoughtHeader label="Thinking…" />
        <ChainOfThoughtContent>
          <ChainOfThoughtStep label="Resolving the port plan" status="running" isLast />
        </ChainOfThoughtContent>
      </ChainOfThought>
    ),
    error: () => (
      <ChainOfThought defaultOpen>
        <ChainOfThoughtHeader label="Chain of thought" />
        <ChainOfThoughtContent>
          <ChainOfThoughtStep
            label="Stream dropped"
            description="The trace ended before the closing step"
            status="pending"
            isLast
          />
        </ChainOfThoughtContent>
      </ChainOfThought>
    ),
  },
  confirmation: {
    populated: () => (
      <Confirmation state="input-available" approval={{ approved: true }} onRespond={() => {}}>
        <ConfirmationRequest>
          <ConfirmationTitle>Install 56 items into apps/example?</ConfirmationTitle>
          <ConfirmationActions>
            <ConfirmationAction action="approve">Install</ConfirmationAction>
            <ConfirmationAction action="deny">Skip</ConfirmationAction>
          </ConfirmationActions>
        </ConfirmationRequest>
      </Confirmation>
    ),
    empty: () => (
      <Confirmation state="input-available">
        <Text className="text-sm text-muted-foreground">
          (no approval requested — the card renders nothing without one)
        </Text>
      </Confirmation>
    ),
    loading: () => (
      <Confirmation state="input-streaming" onRespond={() => {}}>
        <ConfirmationRequest>
          <Shimmer active>
            <Text className="text-sm">Receiving approval request…</Text>
          </Shimmer>
        </ConfirmationRequest>
      </Confirmation>
    ),
    error: () => (
      <Confirmation state="output-error" approval={{ approved: false }} onRespond={() => {}}>
        <ConfirmationRequest>
          <ConfirmationTitle>Install 56 items into apps/example?</ConfirmationTitle>
          <ConfirmationActions>
            <ConfirmationAction action="approve" disabled>
              Install
            </ConfirmationAction>
            <ConfirmationAction action="deny">Cancel</ConfirmationAction>
          </ConfirmationActions>
        </ConfirmationRequest>
      </Confirmation>
    ),
  },
  context: {
    populated: () => (
      <Context usedTokens={142_318} maxTokens={200_000} modelId={MODEL_ID}>
        <ContextTrigger />
      </Context>
    ),
    empty: () => (
      <Context usedTokens={0} maxTokens={200_000} modelId={MODEL_ID}>
        <ContextTrigger />
      </Context>
    ),
    loading: () => (
      <Context usedTokens={1} maxTokens={200_000} modelId={MODEL_ID}>
        <Shimmer active>
          <Text className="text-sm">counting tokens…</Text>
        </Shimmer>
      </Context>
    ),
    error: () => (
      <Context usedTokens={214_500} maxTokens={200_000} modelId={MODEL_ID}>
        <ContextTrigger />
      </Context>
    ),
  },
  image: {
    populated: () => (
      <Image
        uri="https://raw.githubusercontent.com/hackerpug-ai/rnr-ai-elements/v0.2.0/assets/images/icon.png"
        alt="The registry's generated icon"
        width={128}
        height={128}
      />
    ),
    empty: () => (
      <Image
        uri="https://raw.githubusercontent.com/hackerpug-ai/rnr-ai-elements/v0.2.0/assets/images/splash-icon.png"
        alt=""
        width={128}
        height={128}
      />
    ),
    loading: () => (
      <Shimmer active>
        <Text className="text-sm">generating 128×128 icon…</Text>
      </Shimmer>
    ),
    error: () => (
      <Image
        uri="https://raw.githubusercontent.com/hackerpug-ai/rnr-ai-elements/v0.2.0/assets/images/missing.png"
        alt="The image failed to generate"
        width={128}
        height={128}
      />
    ),
  },
  'mic-selector': {
    populated: () => (
      <MicSelector
        routes={[
          { id: 'builtin', label: 'MacBook Pro Microphone', kind: 'builtin' },
          { id: 'airpods', label: 'Justin’s AirPods Pro', kind: 'bluetooth' },
          { id: 'studio', label: 'Mac mini Studio Display', kind: 'other' },
        ]}
        value="airpods"
        onValueChange={() => {}}
      >
        <MicSelectorTrigger />
        <MicSelectorValue placeholder="Pick an input…" />
      </MicSelector>
    ),
    empty: () => (
      <MicSelector routes={[]} value={undefined} onValueChange={() => {}}>
        <MicSelectorTrigger />
        <MicSelectorValue placeholder="No inputs found" />
      </MicSelector>
    ),
    loading: () => (
      <Shimmer active>
        <Text className="text-sm">enumerating audio routes…</Text>
      </Shimmer>
    ),
    error: () => (
      <MicSelector routes={[{ id: 'dead', label: 'Disconnected headset' }]} value={undefined} onValueChange={() => {}}>
        <MicSelectorTrigger />
        <MicSelectorValue placeholder="Input unavailable" />
      </MicSelector>
    ),
  },
  'model-selector': {
    populated: () => (
      <ModelSelector
        models={[
          { id: MODEL_ID, name: 'Fable 5.1', provider: 'Anthropic', description: 'Frontier coding model' },
          { id: 'claude-haiku-4-5-20251001', name: 'Haiku 4.5', provider: 'Anthropic', description: 'Fast and cheap' },
          { id: 'gpt-5.6-sol', name: 'GPT-5.6 Sol', provider: 'OpenAI', description: 'Codex-tuned' },
        ]}
        value={MODEL_ID}
        onValueChange={() => {}}
      >
        <ModelSelectorTrigger />
      </ModelSelector>
    ),
    empty: () => (
      <ModelSelector models={[]} value={undefined} onValueChange={() => {}} placeholder="No models configured">
        <ModelSelectorTrigger />
      </ModelSelector>
    ),
    loading: () => (
      <ModelSelector models={[{ id: 'x', name: 'Loading roster…', provider: '…' }]} value={undefined} onValueChange={() => {}}>
        <ModelSelectorTrigger />
      </ModelSelector>
    ),
    error: () => (
      <ModelSelector models={[]} value={undefined} onValueChange={() => {}} placeholder="Model roster fetch failed">
        <ModelSelectorTrigger />
      </ModelSelector>
    ),
  },
  'open-in-chat': {
    populated: () => (
      <OpenIn query="How do the two registry engines stay in parity?" onOpen={() => {}}>
        <OpenInTrigger />
      </OpenIn>
    ),
    empty: () => (
      <OpenIn query="" onOpen={() => {}}>
        <OpenInTrigger />
      </OpenIn>
    ),
    loading: () => (
      <Shimmer active>
        <Text className="text-sm">building provider URLs…</Text>
      </Shimmer>
    ),
    error: () => (
      <OpenIn query="…" onOpen={() => {}} onOpenError={() => {}}>
        <OpenInTrigger />
      </OpenIn>
    ),
  },
  persona: {
    populated: () => (
      <Persona
        name="Registry Porter"
        description="The agent that installs this library into consumer apps"
        status={MODEL_ID}
        avatarUri={AVATAR_URI}
      />
    ),
    empty: () => <Persona name="(unnamed)" />,
    loading: () => (
      <Shimmer active>
        <Text className="text-sm">loading identity…</Text>
      </Shimmer>
    ),
    error: () => (
      <Persona name="Registry Porter" description="Avatar failed to load" />
    ),
  },
  plan: {
    populated: (o) => (
      <Plan defaultOpen={o.defaultOpen !== false} isStreaming={o.isStreaming === true}>
        <PlanHeader>
          <PlanTitle>Ship the v0.2.0 registry</PlanTitle>
          <PlanDescription>Four steps, all verified against the real CLI</PlanDescription>
          <PlanProgressBadge steps={[{ status: 'completed' }, { status: 'completed' }, { status: 'in_progress' }, { status: 'pending' }]} />
        </PlanHeader>
        <PlanContent>
          <TaskItem status="completed">
            <Text className="text-sm text-foreground">Fix the six dependency declarations</Text>
          </TaskItem>
          <TaskItem status="completed">
            <Text className="text-sm text-foreground">Regenerate both engine trees</Text>
          </TaskItem>
          <TaskItem status="in_progress">
            <Text className="text-sm text-foreground">Install the full set into apps/example</Text>
          </TaskItem>
          <TaskItem status="pending">
            <Text className="text-sm text-foreground">Cut and push the release tag</Text>
          </TaskItem>
        </PlanContent>
      </Plan>
    ),
    empty: () => (
      <Plan>
        <PlanHeader>
          <PlanTitle>(no plan yet)</PlanTitle>
        </PlanHeader>
        <PlanContent />
      </Plan>
    ),
    loading: () => (
      <Plan isStreaming defaultOpen>
        <PlanHeader>
          <Shimmer active>
            <Text className="text-sm">plan streaming…</Text>
          </Shimmer>
        </PlanHeader>
      </Plan>
    ),
    error: () => (
      <Plan defaultOpen>
        <PlanHeader>
          <PlanTitle>Ship the v0.2.0 registry</PlanTitle>
          <PlanDescription>Stream dropped after step two</PlanDescription>
        </PlanHeader>
        <PlanContent>
          <TaskItem status="completed">
            <Text className="text-sm text-foreground">Fix the six dependency declarations</Text>
          </TaskItem>
          <TaskItem status="rejected">
            <Text className="text-sm text-destructive">steps 3-4 never arrived</Text>
          </TaskItem>
        </PlanContent>
      </Plan>
    ),
  },
  queue: {
    populated: () => (
      <Queue onRemove={() => {}}>
        <QueueSection defaultOpen>
          <QueueSectionTrigger label="Queued installs" count={2} />
          <QueueList>
            <QueueItem id="q-1">
              <QueueItemContent>
                <Text className="text-sm text-foreground">terminal.json</Text>
                <QueueItemDescription>ANSI surface · runs after the current install</QueueItemDescription>
              </QueueItemContent>
              <QueueItemRemove label="Remove terminal.json from the queue" />
            </QueueItem>
            <QueueItem id="q-2" completed>
              <QueueItemContent>
                <Text className="text-sm text-foreground">conversation.json</Text>
                <QueueItemDescription>installed from v0.2.0</QueueItemDescription>
              </QueueItemContent>
            </QueueItem>
          </QueueList>
        </QueueSection>
      </Queue>
    ),
    empty: () => (
      <Queue>
        <QueueSection defaultOpen>
          <QueueSectionTrigger label="Queued installs" count={0} />
          <QueueList />
        </QueueSection>
      </Queue>
    ),
    loading: () => (
      <Queue>
        <QueueSection defaultOpen>
          <QueueSectionTrigger label="Queued installs" count={1} />
          <QueueList>
            <QueueItem id="q-loading">
              <QueueItemContent>
                <Shimmer active>
                  <Text className="text-sm">resolving next item…</Text>
                </Shimmer>
              </QueueItemContent>
            </QueueItem>
          </QueueList>
        </QueueSection>
      </Queue>
    ),
    error: () => (
      <Queue>
        <QueueSection defaultOpen>
          <QueueSectionTrigger label="Queued installs" count={1} />
          <QueueList>
            <QueueItem id="q-err">
              <QueueItemContent>
                <Text className="text-sm text-destructive">file-tree.json — registry 404 at the pinned tag</Text>
              </QueueItemContent>
            </QueueItem>
          </QueueList>
        </QueueSection>
      </Queue>
    ),
  },
  question: {
    populated: () => (
      <Question onOptionSelect={() => {}}>
        <QuestionPrompt>Which engine should apps/example install?</QuestionPrompt>
        <QuestionOptions>
          <QuestionOption value="uniwind">uniwind — Tailwind v4</QuestionOption>
          <QuestionOption value="nativewind">nativewind — Tailwind v3</QuestionOption>
          <QuestionOption value="both">Prove both, ship either</QuestionOption>
        </QuestionOptions>
      </Question>
    ),
    empty: () => (
      <Question>
        <QuestionPrompt>(no question asked)</QuestionPrompt>
        <QuestionOptions />
      </Question>
    ),
    loading: () => (
      <Question disabled>
        <Shimmer active>
          <Text className="text-sm">question streaming…</Text>
        </Shimmer>
      </Question>
    ),
    error: () => (
      <Question disabled>
        <QuestionPrompt>Which engine should apps/example install?</QuestionPrompt>
        <QuestionOptions>
          <QuestionOption value="retry">Options failed to load — retry</QuestionOption>
        </QuestionOptions>
      </Question>
    ),
  },
  'speech-input': {
    populated: () => (
      <SpeechInput onTranscriptionChange={() => {}} />
    ),
    empty: () => (
      <SpeechInput onPermissionDenied={() => {}} />
    ),
    loading: () => (
      <Shimmer active>
        <Text className="text-sm">transcribing…</Text>
      </Shimmer>
    ),
    error: () => (
      <SpeechInput onTranscriptionChange={() => {}} onError={() => {}} />
    ),
  },
  'voice-selector': {
    populated: () => (
      <VoiceSelector
        voices={[
          { id: 'alloy', name: 'Alloy', group: 'Neutral', description: 'Balanced and clear', gender: 'female', accent: 'american' },
          { id: 'echo', name: 'Echo', group: 'Neutral', description: 'Warm and even', gender: 'male', accent: 'american' },
          { id: 'fable', name: 'Fable', group: 'Expressive', description: 'British storytelling', gender: 'female', accent: 'british' },
        ]}
        value="alloy"
        onValueChange={() => {}}
      >
        <VoiceSelectorTrigger />
      </VoiceSelector>
    ),
    empty: () => (
      <VoiceSelector voices={[]} value={undefined} onValueChange={() => {}}>
        <VoiceSelectorTrigger />
      </VoiceSelector>
    ),
    loading: () => (
      <Shimmer active>
        <Text className="text-sm">loading voice roster…</Text>
      </Shimmer>
    ),
    error: () => (
      <VoiceSelector
        voices={[{ id: 'broken', name: 'Unavailable voice' }]}
        value={undefined}
        onValueChange={() => {}}
      >
        <VoiceSelectorTrigger />
      </VoiceSelector>
    ),
  },
};
