/**
 * Emits apps/example/gallery/manifest.ts from the registry manifest — the gallery's
 * item list is DERIVED, never hand-edited, so it can never drift from what the
 * registry actually ships.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

function main(): void {
  const root = process.cwd();
  const registry = JSON.parse(
    readFileSync(join(root, 'packages/registry/registry.json'), 'utf8'),
  ) as {
    items: {
      name: string;
      type: string;
      title?: string;
      description?: string;
      dependencies?: string[];
      meta?: { permissions?: { ios?: string[]; android?: string[] } };
    }[];
  };

  /**
   * Native modules Expo Go ships (SDK 57 bundled set). Everything else an item
   * declares is JS-only, so any dependency outside this list that isn't pure
   * JS means the item needs a dev client — surfaced, never silently skipped.
   */
  const EXPO_GO_NATIVE = new Set([
    'react-native-reanimated',
    'react-native-worklets',
    'react-native-gesture-handler',
    'react-native-screens',
    'react-native-safe-area-context',
    'react-native-webview',
  ]);
  const isJsOnly = (dep: string) =>
    dep.startsWith('expo-') ||
    dep.startsWith('@rn-primitives/') ||
    dep === 'class-variance-authority';

  const kindOrder = { component: 0, ui: 1, lib: 2 } as const;
  type Kind = keyof typeof kindOrder;
  const items = registry.items
    .map((i) => ({
      name: i.name,
      kind: i.type.replace('registry:', '') as Kind,
      title: i.title ?? i.name,
      description: i.description ?? '',
      dependencies: i.dependencies ?? [],
      permissions: i.meta?.permissions ?? {},
      expoGo: (i.dependencies ?? []).every((d) => EXPO_GO_NATIVE.has(d) || isJsOnly(d)),
    }))
    .filter((i) => i.kind in kindOrder)
    .sort((a, b) => kindOrder[a.kind] - kindOrder[b.kind] || a.name.localeCompare(b.name));

  const out = `// GENERATED by scripts/build-gallery-manifest.ts — do not edit; re-run \`pnpm gallery:manifest\`.
export type GalleryItem = {
  name: string;
  kind: 'component' | 'ui' | 'lib';
  title: string;
  description: string;
  dependencies: string[];
  permissions: { ios?: string[]; android?: string[] };
  /** True when every declared dependency ships in Expo Go or is pure JS. */
  expoGo: boolean;
};
export const GALLERY_ITEMS: GalleryItem[] = ${JSON.stringify(items, null, 2)};
`;
  writeFileSync(join(root, 'apps/example/gallery/manifest.ts'), out);
  console.log(
    `gallery manifest — ${items.length} item(s) (${Object.values(kindOrder).length} kinds) -> apps/example/gallery/manifest.ts`,
  );
}

main();
