/// <reference types="uniwind/types" />

// Side-effect CSS imports (the Uniwind entry file).
declare module '*.css';
declare module '@/global.css';

// RNR's input.tsx and textarea.tsx pass `placeholderClassName`, which Uniwind's
// generated types do not currently declare on TextInputProps. Augment rather than
// edit the generated file, which is regenerated by Metro on every bundle.
import 'react-native';
declare module 'react-native' {
  interface TextInputProps {
    placeholderClassName?: string;
  }
}
